name: uble-db

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ubleuser
      POSTGRES_PASSWORD: ublepwd
      POSTGRES_DB: uble-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: