name: uble-db

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ubleuser
      POSTGRES_PASSWORD: ublepwd
      POSTGRES_DB: uble-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "ublepwd"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
